#!/usr/bin/env php
<?php
    require_once __DIR__ . '/vendor/autoload.php';

    use Symfony\Component\Console\Application;
    use WeatherGetter\WeatherGetterCommand;

    $app = new Application('Weather Getter', '1.0');
    $app->add(new WeatherGetterCommand());
    $app->run();